#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CerberusAndroid.Resource", IsApplication=true)]

namespace CerberusAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonLogInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cerberusLogo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dummy = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mail = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProgressBarStyle = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070016
			public const int AddButton = 2131165206;
			
			// aapt resource value: 0x7f07002c
			public const int CancelDeleteButton = 2131165228;
			
			// aapt resource value: 0x7f070026
			public const int NameLabel = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int NameText = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int NotesLabel = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int NotesText = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int SaveButton = 2131165227;
			
			// aapt resource value: 0x7f070025
			public const int TaskDetailsHeader = 2131165221;
			
			// aapt resource value: 0x7f070017
			public const int TaskList = 2131165207;
			
			// aapt resource value: 0x7f070002
			public const int btnDialogLogIn = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int btnDialogSignUpWithEmail = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int btnEmployeeEvents = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int btnEmployeeHistory = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int btnEmployeeProfile = 2131165200;
			
			// aapt resource value: 0x7f07001d
			public const int btnLogIn = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int btnSignUpWithEmail = 2131165215;
			
			// aapt resource value: 0x7f07002a
			public const int chkDone = 2131165226;
			
			// aapt resource value: 0x7f07001c
			public const int demoImageView = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int eventDateItemTxtView = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int eventDateTextView = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int eventNameItemTxtViewId = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int eventNameTextView = 2131165210;
			
			// aapt resource value: 0x7f07000b
			public const int imageButton1 = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int imageView1 = 2131165194;
			
			// aapt resource value: 0x7f070021
			public const int item_subtitle = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int item_title = 2131165218;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout2 = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout3 = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int listViewUpcomingEvents = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int llContainer = 2131165202;
			
			// aapt resource value: 0x7f07002d
			public const int lstItemTask = 2131165229;
			
			// aapt resource value: 0x7f070011
			public const int pastEventsListView = 2131165201;
			
			// aapt resource value: 0x7f070020
			public const int progressBar1 = 2131165216;
			
			// aapt resource value: 0x7f070007
			public const int sample_content_fragment = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int sample_main_layout = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int sliding_tabs = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int txtEmail = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int txtEmployeeGreetings = 2131165196;
			
			// aapt resource value: 0x7f07001e
			public const int txtOr = 2131165214;
			
			// aapt resource value: 0x7f070004
			public const int txtPassword = 2131165188;
			
			// aapt resource value: 0x7f070024
			public const int txtUpcomingEventDate = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int txtUpcomingEventName = 2131165219;
			
			// aapt resource value: 0x7f070000
			public const int txtUsername = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int txtUsernamePassword = 2131165185;
			
			// aapt resource value: 0x7f070015
			public const int viewpager = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_signup = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EmployeeEventsTabsPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EmployeeHomeScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EmployeePastEvents = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EmployeeProfile = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EmployeeUpcomingEvents = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_sample = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HomeScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ItemView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int listview_row = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LogIn = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int pager_item = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int row_upcomingEvent = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int TaskDetails = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TaskListItem = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int CustomActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int MyActionBar = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
